"""
MIDI Engine
Responsible for creating MIDI files from musical data generated by the modules.
"""

from __future__ import annotations

from pathlib import Path
from typing import Dict, Iterable, List, Optional, Tuple, Union

import mido
from mido import Message, MetaMessage, MidiFile, MidiTrack

from config.settings import BEATS_PER_BAR, DEFAULTS, OUTPUT, TICKS_PER_BEAT, get_mix
from core.models import Note

# Ordering of simultaneous events: note-offs first, then controllers, then note-ons.
_ORDER = {"note_off": 0, "control_change": 1, "program_change": 1, "note_on": 2}

NoteLike = Union[Dict, Note]


class MidiEngine:
    def __init__(self, bpm: float = DEFAULTS["bpm"], ticks_per_beat: int = TICKS_PER_BEAT):
        self.bpm = bpm
        self.ticks_per_beat = ticks_per_beat
        self.tracks: Dict[str, Dict] = {}          # name -> {"channel", "events": [(tick, order, msg)]}
        self._meta: List[Tuple[int, MetaMessage]] = []
        self.key: Optional[str] = None

    # ------------------------------------------------------------------ helpers
    def _ticks(self, beats: float) -> int:
        return max(0, int(round(beats * self.ticks_per_beat)))

    def _create_track(self, name: str, channel: int = 0, program: Optional[int] = None) -> Dict:
        track = {"channel": channel, "events": []}
        self.tracks[name] = track
        if program is not None and channel != 9:
            track["events"].append((0, _ORDER["program_change"],
                                    Message("program_change", program=program, channel=channel)))
        return track

    def _track(self, name: str, channel: int, program: Optional[int] = None) -> Dict:
        return self.tracks.get(name) or self._create_track(name, channel, program)

    # ------------------------------------------------------------------ public API
    def add_notes(self, track_name: str, notes: Iterable[NoteLike], channel: int = 0, program: int = 0) -> None:
        """
        Add a list of notes to a track.

        Each note may be a :class:`core.models.Note` or a dict with:
        {
            "note": int (0-127),
            "start": float (in beats),
            "duration": float (in beats),
            "velocity": int (1-127)
        }
        """
        track = self._track(track_name, channel, program)
        parsed = []
        for note in notes:
            if isinstance(note, Note):
                pitch, start, dur, vel = note.pitch, note.start, note.duration, note.velocity
            else:
                pitch, start, dur = note["note"], note["start"], note["duration"]
                vel = note.get("velocity", 100)
            on = self._ticks(start)
            off = max(on + 1, self._ticks(start + dur))
            parsed.append([on, off, max(0, min(127, int(pitch))), max(1, min(127, int(vel)))])

        # Overlapping notes of the same pitch would be cut by the earlier note-off:
        # end the previous one where the next one starts instead.
        parsed.sort(key=lambda n: (n[0], n[2]))
        last: Dict[int, list] = {}
        for n in parsed:
            prev = last.get(n[2])
            if prev is not None and prev[1] > n[0]:
                prev[1] = n[0]
            last[n[2]] = n
        for on, off, pitch, vel in parsed:
            if off <= on:
                continue
            track["events"].append((on, _ORDER["note_on"],
                                    Message("note_on", note=pitch, velocity=vel, channel=channel)))
            track["events"].append((off, _ORDER["note_off"],
                                    Message("note_off", note=pitch, velocity=0, channel=channel)))

    def add_control_change(self, track_name: str, control: int, value: int, time_in_beats: float,
                           channel: int = 0) -> None:
        """Add a Control Change message (useful for filter cutoff, modulation, etc.)."""
        track = self._track(track_name, channel)
        track["events"].append((self._ticks(time_in_beats), _ORDER["control_change"],
                                Message("control_change", control=int(control),
                                        value=max(0, min(127, int(value))), channel=channel)))

    def add_marker(self, text: str, time_in_beats: float) -> None:
        self._meta.append((self._ticks(time_in_beats), MetaMessage("marker", text=text)))

    def set_key(self, key: str) -> None:
        """Key signature, e.g. ``"Am"`` / ``"F#m"`` / ``"E"`` (ignored if mido rejects it)."""
        self.key = key

    def build(self) -> MidiFile:
        """Assemble a type-1 :class:`mido.MidiFile` (conductor track + one track per part)."""
        mid = MidiFile(type=1, ticks_per_beat=self.ticks_per_beat)
        conductor = MidiTrack()
        conductor.append(MetaMessage("track_name", name="Tempo", time=0))
        conductor.append(MetaMessage("set_tempo", tempo=mido.bpm2tempo(self.bpm), time=0))
        conductor.append(MetaMessage("time_signature", numerator=BEATS_PER_BAR, denominator=4, time=0))
        if self.key:
            try:
                conductor.append(MetaMessage("key_signature", key=self.key, time=0))
            except (ValueError, KeyError):
                pass
        now = 0
        for tick, msg in sorted(self._meta, key=lambda m: m[0]):
            conductor.append(msg.copy(time=tick - now))
            now = tick
        mid.tracks.append(conductor)

        for name, track in self.tracks.items():
            mt = MidiTrack()
            mt.name = name
            now = 0
            for tick, _, msg in sorted(track["events"], key=lambda e: (e[0], e[1])):
                mt.append(msg.copy(time=tick - now))
                now = tick
            mid.tracks.append(mt)
        return mid

    @property
    def mid(self) -> MidiFile:
        return self.build()

    def save(self, filename: str, output_dir: Optional[Union[str, Path]] = None) -> str:
        """Save the MIDI file and return the full path."""
        if output_dir is None:
            output_dir = OUTPUT["midi_folder"]

        output_path = Path(output_dir)
        output_path.mkdir(parents=True, exist_ok=True)

        full_path = output_path / filename
        if full_path.suffix.lower() not in (".mid", ".midi"):
            full_path = full_path.with_name(full_path.name + ".mid")

        self.build().save(str(full_path))
        return str(full_path)

    def get_total_beats(self) -> float:
        """Return approximate total length in beats."""
        max_ticks = 0
        for track in self.tracks.values():
            for tick, _, _ in track["events"]:
                max_ticks = max(max_ticks, tick)
        return max_ticks / self.ticks_per_beat


def song_to_midi(song) -> MidiEngine:
    """Convert a generated :class:`core.models.Song` into a :class:`MidiEngine`."""
    engine = MidiEngine(bpm=song.bpm)
    engine.set_key(song.key)
    for section in song.arrangement.sections:
        engine.add_marker(section.label, section.start_beat)
    for track in song.tracks:
        engine._create_track(track.name, track.channel, track.program)
        mix = get_mix(track.name)
        volume = int(max(0, min(127, round(100 * 10 ** (mix.volume_db / 40)))))
        engine.add_control_change(track.name, 7, volume, 0, track.channel)
        engine.add_control_change(track.name, 10, int(round(64 + 63 * mix.pan)), 0, track.channel)
        engine.add_notes(track.name, track.notes, channel=track.channel, program=track.program)
        for cc in track.controls:
            engine.add_control_change(track.name, cc.controller, cc.value, cc.time, track.channel)
    return engine


# Convenience function
def create_midi_engine(bpm: float = DEFAULTS["bpm"]) -> MidiEngine:
    return MidiEngine(bpm=bpm)
